# Generated by Django 4.2.13 on 2025-08-25 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'application_approved_email'", max_length=100, unique=True, verbose_name='Template Name')),
                ('type', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS')], max_length=10, verbose_name='Type')),
                ('subject', models.CharField(blank=True, help_text='For emails only.', max_length=255, verbose_name='Subject')),
                ('body', models.TextField(help_text='Use placeholders like {{ full_name }} or {{ tracking_code }}.', verbose_name='Body')),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
            },
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_type', models.CharField(choices=[('UNIVERSITY', 'University'), ('AZFA', 'AZFA Center'), ('RECRUITMENT', 'Recruitment Institution')], max_length=20, verbose_name='Permit Type')),
                ('institution_name', models.CharField(max_length=255, verbose_name='Institution Name')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('PENDING', 'Pending Review')], default='PENDING', max_length=20, verbose_name='Status')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Issue Date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('permit_number', models.CharField(max_length=50, unique=True, verbose_name='Permit Number')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Stores type-specific data.', verbose_name='Details')),
            ],
            options={
                'verbose_name': 'Permit',
                'verbose_name_plural': 'Permits',
            },
        ),
        migrations.CreateModel(
            name='SystemList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'nationalities'", max_length=100, unique=True, verbose_name='List Name')),
                ('items', models.JSONField(default=list, help_text='A JSON array of strings or objects.', verbose_name='Items')),
            ],
            options={
                'verbose_name': 'System List',
                'verbose_name_plural': 'System Lists',
            },
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Program Name'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='University Name'),
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Scholarship Title')),
                ('field_of_study', models.CharField(max_length=255, verbose_name='Field of Study')),
                ('description', models.TextField(verbose_name='Description')),
                ('duration', models.CharField(max_length=100, verbose_name='Duration')),
                ('financial_coverage', models.CharField(max_length=255, verbose_name='Financial Coverage')),
                ('application_deadline', models.DateField(verbose_name='Application Deadline')),
                ('requirements', models.JSONField(default=list, verbose_name='Requirements')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='core.university')),
            ],
            options={
                'verbose_name': 'Scholarship',
                'verbose_name_plural': 'Scholarships',
                'ordering': ['-application_deadline', 'title'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Unit Name')),
                ('type', models.CharField(choices=[('ORGANIZATION', 'Organization'), ('PROVINCE', 'Province'), ('UNIVERSITY', 'University')], max_length=20, verbose_name='Unit Type')),
                ('manager_name', models.CharField(blank=True, max_length=255, verbose_name='Manager Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.organizationunit', verbose_name='Parent Unit')),
            ],
            options={
                'verbose_name': 'Organization Unit',
                'verbose_name_plural': 'Organization Units',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField(blank=True, help_text='Optional link to a relevant page', verbose_name='Link')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-timestamp'],
            },
        ),
    ]
