# Generated by Django 4.2.13 on 2025-08-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notificationtemplate_permit_systemlist_and_more'),
    ]

    operations = [
    ]
