# Generated by Django 4.2.13 on 2025-08-25 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notificationtemplate_permit_systemlist_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(help_text='e.g., view_all_applications', max_length=100, unique=True, verbose_name='Codename')),
                ('name', models.CharField(help_text='e.g., Can view all applications', max_length=255, verbose_name='Name')),
                ('group', models.CharField(help_text="A group name for UI organization, e.g., 'applications'", max_length=100, verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['group', 'name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='organization_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='core.organizationunit', verbose_name='Organization Unit'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Role Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='universities',
            field=models.ManyToManyField(blank=True, related_name='experts', to='core.university', verbose_name='Affiliated Universities'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Not used for login.', max_length=150, verbose_name='username'),
        ),
        migrations.CreateModel(
            name='UserNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_on_new_task', models.BooleanField(default=True, verbose_name='Email on new task assignment')),
                ('email_on_status_update', models.BooleanField(default=False, verbose_name='Email on application status update')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Notification Settings',
                'verbose_name_plural': 'User Notification Settings',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='users.permission', verbose_name='Permissions'),
        ),
    ]
