# Generated by Django 4.2.13 on 2025-08-25 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_permission_user_organization_unit_user_phone_number_and_more'),
    ]

    operations = [
    ]
