# Generated by Django 4.2.13 on 2025-08-25 13:08

import apps.applications.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_level', models.CharField(max_length=100, verbose_name='مقطع تحصیلی')),
                ('country', models.CharField(max_length=100, verbose_name='کشور محل تحصیل')),
                ('university_name', models.CharField(max_length=255, verbose_name='دانشگاه محل تحصیل')),
                ('field_of_study', models.CharField(max_length=255, verbose_name='رشته و گرایش')),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='معدل')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='academic_certs/', verbose_name='فایل مدرک')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(default=apps.applications.models.generate_tracking_code, editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'در انتظار بررسی کارشناس'), ('PENDING_CORRECTION', 'در انتظار اصلاح توسط متقاضی'), ('APPROVED', 'تایید شده'), ('REJECTED', 'رد شده')], default='PENDING_REVIEW', max_length=50)),
                ('full_name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('date_of_birth', models.DateField(verbose_name='تاریخ تولد')),
                ('country_of_residence', models.CharField(max_length=100, verbose_name='کشور محل اقامت')),
                ('father_name', models.CharField(max_length=255, verbose_name='نام پدر')),
                ('grandfather_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام جد')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100, verbose_name='نوع مدرک')),
                ('file', models.FileField(upload_to='application_docs/', verbose_name='فایل')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='اقدام')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UniversityChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(verbose_name='اولویت')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_choices', to='applications.application')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.program', verbose_name='رشته')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.university', verbose_name='دانشگاه')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UNCLAIMED', 'در انتظار ارجاع'), ('ASSIGNED', 'ارجاع شده'), ('COMPLETED', 'تکمیل شده')], default='UNCLAIMED', max_length=20)),
                ('decision', models.CharField(choices=[('PENDING', 'در انتظار تصمیم'), ('APPROVED', 'تایید شده'), ('REJECTED', 'رد شده')], default='PENDING', max_length=20)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='applications.application')),
            ],
        ),
    ]
