# Generated by Django 4.2.13 on 2025-08-25 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notificationtemplate_permit_systemlist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_type',
            field=models.CharField(choices=[('NEW_ADMISSION', 'New Admission'), ('VISA_EXTENSION', 'Visa Extension'), ('INTERNAL_EXIT_PERMIT', 'Internal Exit Permit'), ('FINAL_EXIT_PERMIT', 'Final Exit Permit'), ('TRANSFER_REQUEST', 'Transfer Request')], default='NEW_ADMISSION', max_length=50, verbose_name='Application Type'),
        ),
        migrations.AddField(
            model_name='application',
            name='form_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Form Data'),
        ),
        migrations.AddField(
            model_name='application',
            name='submitted_by_institution',
            field=models.ForeignKey(blank=True, help_text='The institution user that submitted this application.', limit_choices_to={'roles__name': 'Recruitment Institution'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='academichistory',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='academic_certs/', verbose_name='Certificate File'),
        ),
        migrations.AlterField(
            model_name='academichistory',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Country of Study'),
        ),
        migrations.AlterField(
            model_name='academichistory',
            name='degree_level',
            field=models.CharField(max_length=100, verbose_name='Degree Level'),
        ),
        migrations.AlterField(
            model_name='academichistory',
            name='field_of_study',
            field=models.CharField(max_length=255, verbose_name='Field of Study'),
        ),
        migrations.AlterField(
            model_name='academichistory',
            name='gpa',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='GPA'),
        ),
        migrations.AlterField(
            model_name='academichistory',
            name='university_name',
            field=models.CharField(max_length=255, verbose_name='University Name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='country_of_residence',
            field=models.CharField(blank=True, max_length=100, verbose_name='Country of Residence'),
        ),
        migrations.AlterField(
            model_name='application',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='application',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, verbose_name="Father's Name"),
        ),
        migrations.AlterField(
            model_name='application',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='grandfather_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Grandfather's Name"),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('PENDING_CORRECTION', 'Pending Correction by Applicant'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_REVIEW', max_length=50),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='document_type',
            field=models.CharField(max_length=100, verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='file',
            field=models.FileField(upload_to='application_docs/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='applicationlog',
            name='action',
            field=models.CharField(max_length=255, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='applicationlog',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='applicationtask',
            name='decision',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='applicationtask',
            name='status',
            field=models.CharField(choices=[('UNCLAIMED', 'Unclaimed'), ('ASSIGNED', 'Assigned'), ('COMPLETED', 'Completed')], default='UNCLAIMED', max_length=20),
        ),
        migrations.AlterField(
            model_name='universitychoice',
            name='priority',
            field=models.PositiveSmallIntegerField(verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='universitychoice',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.program', verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='universitychoice',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.university', verbose_name='University'),
        ),
        migrations.CreateModel(
            name='InternalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes', to='applications.application')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Internal Note',
                'verbose_name_plural': 'Internal Notes',
                'ordering': ['-timestamp'],
            },
        ),
    ]
